package cli

import (
	"fmt"
	"io"
	"os"
	"strings"
)

// completionFlags lists the flags offered per canonical command name.
var completionFlags = map[string][]string{
	"install":  {"-g", "--global", "-w", "--workspace", "--"},
	"run":      {"-w", "--workspace"},
	"outdated": {"--json", "--all", "--workspace", "-w"},
	"audit":    {"--json", "--timeout", "--workspace", "-w"},
	"graph":    {"--json", "--svg", "--depth", "--exec", "--workspace", "-w"},
	"lock":     {"--verify"},
	"man":      {"--generate"},
}

// completionSubcommands lists the arguments completed after a command's name.
var completionSubcommands = map[string][]string{
	"completion": {"bash", "zsh", "fish"},
	"config":     {"show", "path", "edit", "set", "reset"},
	"env":        {"install", "use", "list", "ls-remote", "current", "remove"},
}

// completionWords returns every command name and alias that can start with a
// letter, in table order and without duplicates.
func completionWords() []string {
	var words []string
	seen := map[string]bool{}
	add := func(w string) {
		if strings.HasPrefix(w, "-") || seen[w] {
			return
		}
		seen[w] = true
		words = append(words, w)
	}
	for _, c := range commandTable {
		add(c.name)
		for _, a := range c.aliases {
			add(a)
		}
	}
	return words
}

// commandNames returns the canonical command names in table order.
func commandNames() []string {
	names := make([]string, 0, len(commandTable))
	for _, c := range commandTable {
		names = append(names, c.name)
	}
	return names
}

// subcommandWords returns what follows a command's name: the canonical command
// names for man, otherwise completionSubcommands.
func subcommandWords(name string) []string {
	if name == "man" {
		return commandNames()
	}
	return completionSubcommands[name]
}

// namesWithAliases returns the command name followed by its aliases.
func (c commandInfo) namesWithAliases() []string {
	return append([]string{c.name}, c.aliases...)
}

// writeCompletion writes the completion script for shell to w.
func writeCompletion(w io.Writer, shell string) error {
	var sb strings.Builder
	switch shell {
	case "bash":
		writeBashCompletion(&sb)
	case "zsh":
		writeZshCompletion(&sb)
	case "fish":
		writeFishCompletion(&sb)
	default:
		return fmt.Errorf("unsupported shell %q (want bash, zsh or fish)", shell)
	}
	_, err := io.WriteString(w, sb.String())
	return err
}

// writeCaseBlocks emits the shared POSIX-style case statements that set
// $flags (by canonical command, aliases resolved) and $subs (by canonical name).
func writeCaseBlocks(sb *strings.Builder, indent string) {
	sb.WriteString(indent + "case \"$cmd\" in\n")
	for _, c := range commandTable {
		if flags := completionFlags[c.name]; len(flags) > 0 {
			fmt.Fprintf(sb, "%s    %s) flags=%q ;;\n", indent, strings.Join(c.namesWithAliases(), "|"), strings.Join(flags, " "))
		}
	}
	sb.WriteString(indent + "esac\n")
	sb.WriteString(indent + "case \"$cmd\" in\n")
	for _, c := range commandTable {
		if subs := subcommandWords(c.name); len(subs) > 0 {
			fmt.Fprintf(sb, "%s    %s) subs=%q ;;\n", indent, strings.Join(c.namesWithAliases(), "|"), strings.Join(subs, " "))
		}
	}
	sb.WriteString(indent + "esac\n")
}

func writeBashCompletion(sb *strings.Builder) {
	sb.WriteString("# bash completion for xpm; generated by `xpm completion bash`\n")
	sb.WriteString("_xpm() {\n")
	sb.WriteString("    local cur cmd flags subs\n")
	sb.WriteString("    COMPREPLY=()\n")
	sb.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	sb.WriteString("    if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	fmt.Fprintf(sb, "        COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(completionWords(), " "))
	sb.WriteString("        return 0\n")
	sb.WriteString("    fi\n")
	sb.WriteString("    cmd=\"${COMP_WORDS[1]}\"\n")
	sb.WriteString("    flags=\"\"\n")
	sb.WriteString("    subs=\"\"\n")
	writeCaseBlocks(sb, "    ")
	sb.WriteString("    case \"$cur\" in\n")
	sb.WriteString("        -*)\n")
	sb.WriteString("            COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n")
	sb.WriteString("            ;;\n")
	sb.WriteString("        *)\n")
	sb.WriteString("            if [ \"$COMP_CWORD\" -eq 2 ] && [ -n \"$subs\" ]; then\n")
	sb.WriteString("                COMPREPLY=( $(compgen -W \"$subs\" -- \"$cur\") )\n")
	sb.WriteString("            fi\n")
	sb.WriteString("            ;;\n")
	sb.WriteString("    esac\n")
	sb.WriteString("    return 0\n")
	sb.WriteString("}\n")
	sb.WriteString("complete -o default -F _xpm xpm\n")
}

func writeZshCompletion(sb *strings.Builder) {
	sb.WriteString("#compdef xpm\n")
	sb.WriteString("# zsh completion for xpm; generated by `xpm completion zsh`\n")
	sb.WriteString("_xpm() {\n")
	sb.WriteString("    local cur cmd flags subs\n")
	sb.WriteString("    cur=\"${words[CURRENT]}\"\n")
	sb.WriteString("    if [ \"$CURRENT\" -eq 2 ]; then\n")
	fmt.Fprintf(sb, "        compadd -- %s\n", strings.Join(completionWords(), " "))
	sb.WriteString("        return 0\n")
	sb.WriteString("    fi\n")
	sb.WriteString("    cmd=\"${words[2]}\"\n")
	sb.WriteString("    flags=\"\"\n")
	sb.WriteString("    subs=\"\"\n")
	writeCaseBlocks(sb, "    ")
	sb.WriteString("    case \"$cur\" in\n")
	sb.WriteString("        -*)\n")
	sb.WriteString("            compadd -- ${=flags}\n")
	sb.WriteString("            ;;\n")
	sb.WriteString("        *)\n")
	sb.WriteString("            if [ \"$CURRENT\" -eq 3 ] && [ -n \"$subs\" ]; then\n")
	sb.WriteString("                compadd -- ${=subs}\n")
	sb.WriteString("            else\n")
	sb.WriteString("                _files\n")
	sb.WriteString("            fi\n")
	sb.WriteString("            ;;\n")
	sb.WriteString("    esac\n")
	sb.WriteString("}\n")
	sb.WriteString("if [ \"$funcstack[1]\" = \"_xpm\" ]; then\n")
	sb.WriteString("    _xpm \"$@\"\n")
	sb.WriteString("else\n")
	sb.WriteString("    compdef _xpm xpm\n")
	sb.WriteString("fi\n")
}

// fishQuote single-quotes s for fish.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

func writeFishCompletion(sb *strings.Builder) {
	sb.WriteString("# fish completion for xpm; generated by `xpm completion fish`\n")
	for _, c := range commandTable {
		for _, n := range c.namesWithAliases() {
			if strings.HasPrefix(n, "-") {
				continue
			}
			fmt.Fprintf(sb, "complete -c xpm -f -n __fish_use_subcommand -a %s -d %s\n", fishQuote(n), fishQuote(c.description))
		}
	}
	for _, c := range commandTable {
		var seen []string
		for _, n := range c.namesWithAliases() {
			if !strings.HasPrefix(n, "-") {
				seen = append(seen, n)
			}
		}
		cond := fishQuote("__fish_seen_subcommand_from " + strings.Join(seen, " "))
		for _, f := range completionFlags[c.name] {
			switch {
			case f == "--":
			case strings.HasPrefix(f, "--"):
				fmt.Fprintf(sb, "complete -c xpm -n %s -l %s\n", cond, strings.TrimPrefix(f, "--"))
			case strings.HasPrefix(f, "-"):
				fmt.Fprintf(sb, "complete -c xpm -n %s -s %s\n", cond, strings.TrimPrefix(f, "-"))
			}
		}
		if subs := subcommandWords(c.name); len(subs) > 0 {
			fmt.Fprintf(sb, "complete -c xpm -f -n %s -a %s\n", cond, fishQuote(strings.Join(subs, " ")))
		}
	}
}

// cmdCompletion implements `xpm completion <bash|zsh|fish>`.
func cmdCompletion(args []string) int {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "error: completion needs exactly one argument: bash, zsh or fish")
		showCommandUsage("completion")
		return 2
	}
	if err := writeCompletion(os.Stdout, args[0]); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		showCommandUsage("completion")
		return 2
	}
	return 0
}
