package doctor

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

const (
	pkgJSONExpressJest = `{
  "name": "app",
  "version": "1.0.0",
  "dependencies": {"express": "^4.18.2"},
  "devDependencies": {"jest": "^29.7.0"}
}`
	npmLockExpressJest = `{
  "name": "app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "app",
      "version": "1.0.0",
      "dependencies": {"express": "^4.18.2"},
      "devDependencies": {"jest": "^29.7.0"}
    },
    "node_modules/express": {"version": "4.18.2"},
    "node_modules/jest": {"version": "29.7.0", "dev": true}
  }
}`
	npmLockV1 = `{
  "name": "app",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {"express": {"version": "4.18.2"}}
}`
	pnpmV9ExpressJest = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      express:
        specifier: ^4.18.2
        version: 4.18.2
    devDependencies:
      jest:
        specifier: ^29.7.0
        version: 29.7.0

packages:

  express@4.18.2:
    resolution: {integrity: sha512-aaaa}

  jest@29.7.0:
    resolution: {integrity: sha512-bbbb}
`
	pnpmV6ExpressOnly = `lockfileVersion: '6.0'

dependencies:
  express:
    specifier: ^4.18.2
    version: 4.18.2

packages:

  /express@4.18.2:
    resolution: {integrity: sha512-aaaa}
    dev: false
`
	cargoToml = `[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
json = { package = "serde_json", version = "1" }

[dev-dependencies]
tempfile = "3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[workspace.dependencies]
unused-by-members = "1"
`
	cargoLockFull = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "app"
version = "0.1.0"

[[package]]
name = "libc"
version = "0.2.153"

[[package]]
name = "serde"
version = "1.0.197"

[[package]]
name = "serde_json"
version = "1.0.114"

[[package]]
name = "tempfile"
version = "3.10.1"
`
	goModTwoRequires = `module example.com/app

go 1.22

require (
	github.com/BurntSushi/toml v1.3.2
	gopkg.in/yaml.v3 v3.0.1 // indirect
)

require example.com/local v0.0.0

replace example.com/local => ../local
`
	goSumTwoRequires = `github.com/BurntSushi/toml v1.3.2 h1:o7IhLm0Msx3BaB+n3Ag7L8EVlByGnpq14C4YWiu/gL8=
github.com/BurntSushi/toml v1.3.2/go.mod h1:CxXYINrC8qIiEnFrOxCa7Jy5BFHlXnUU2pbicEuybxQ=
gopkg.in/yaml.v3 v3.0.1/go.mod h1:K4uyk7z7BCEPqu6E4C/ADh5gWJ+FNkKDhzpBmIfmJlc=
`
)

func TestCheckDriftComparesContents(t *testing.T) {
	cases := []struct {
		name   string
		files  map[string]string
		status DriftStatus
		detail string
	}{
		{"npm v3 aligned", map[string]string{"package.json": pkgJSONExpressJest, "package-lock.json": npmLockExpressJest}, DriftStatusOK, ""},
		{"npm dependency added to package.json", map[string]string{
			"package.json":      strings.Replace(pkgJSONExpressJest, `"express": "^4.18.2"`, `"express": "^4.18.2", "lodash": "^4.17.21"`, 1),
			"package-lock.json": npmLockExpressJest,
		}, DriftStatusOutdated, "in package.json but not package-lock.json: lodash"},
		{"npm dependency removed from package.json", map[string]string{
			"package.json": strings.Replace(pkgJSONExpressJest, `,
  "devDependencies": {"jest": "^29.7.0"}`, "", 1),
			"package-lock.json": npmLockExpressJest,
		}, DriftStatusOutdated, "in package-lock.json but not package.json: jest"},
		{"npm lockfile v1 is not compared", map[string]string{"package.json": pkgJSONExpressJest, "package-lock.json": npmLockV1}, DriftStatusUnknown, "lockfileVersion 1 has no root entry; contents not compared"},
		{"npm lockfile malformed", map[string]string{"package.json": pkgJSONExpressJest, "package-lock.json": "{"}, DriftStatusInvalid, "package-lock.json: unexpected end of JSON input"},
		{"pnpm v9 importers aligned", map[string]string{"package.json": pkgJSONExpressJest, "pnpm-lock.yaml": pnpmV9ExpressJest}, DriftStatusOK, ""},
		{"pnpm v6 single project lacks jest", map[string]string{"package.json": pkgJSONExpressJest, "pnpm-lock.yaml": pnpmV6ExpressOnly}, DriftStatusOutdated, "in package.json but not pnpm-lock.yaml: jest"},
		{"yarn is not compared", map[string]string{"package.json": pkgJSONExpressJest, "yarn.lock": "# yarn lockfile v1\n"}, DriftStatusUnknown, "contents not compared"},
		{"cargo aligned (rename, target deps)", map[string]string{"Cargo.toml": cargoToml, "Cargo.lock": cargoLockFull}, DriftStatusOK, ""},
		{"cargo lock lacks a dependency", map[string]string{"Cargo.toml": cargoToml, "Cargo.lock": strings.Replace(cargoLockFull, "name = \"libc\"", "name = \"other\"", 1)}, DriftStatusOutdated, "in Cargo.toml but not Cargo.lock: libc"},
		{"go aligned (replaced module skipped)", map[string]string{"go.mod": goModTwoRequires, "go.sum": goSumTwoRequires}, DriftStatusOK, ""},
		{"go version bumped without tidy", map[string]string{"go.mod": strings.Replace(goModTwoRequires, "toml v1.3.2", "toml v1.4.0", 1), "go.sum": goSumTwoRequires}, DriftStatusOutdated, "in go.mod but not go.sum: github.com/BurntSushi/toml v1.4.0"},
		{"composer parses", map[string]string{"composer.json": "{}", "composer.lock": `{"packages": []}`}, DriftStatusUnknown, "lockfile parses; contents not compared"},
		{"composer malformed", map[string]string{"composer.json": "{}", "composer.lock": "{"}, DriftStatusInvalid, "unexpected end of JSON input"},
		{"uv.lock parses", map[string]string{"pyproject.toml": "[project]\nname = \"x\"\n", "uv.lock": "version = 1\n"}, DriftStatusUnknown, "lockfile parses; contents not compared"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir, _ := projectWith(t, c.files)
			got := CheckDrift(dir)
			if len(got) != 1 {
				t.Fatalf("CheckDrift = %+v, want one result", got)
			}
			if got[0].Status != c.status || got[0].Detail != c.detail {
				t.Errorf("CheckDrift = status %v detail %q, want %v %q", got[0].Status, got[0].Detail, c.status, c.detail)
			}
		})
	}
}

func TestCheckDriftIgnoresModificationTimes(t *testing.T) {
	dir, _ := projectWith(t, map[string]string{"package.json": pkgJSONExpressJest, "package-lock.json": npmLockExpressJest})
	past := time.Now().Add(-48 * time.Hour)
	if err := os.Chtimes(filepath.Join(dir, "package-lock.json"), past, past); err != nil {
		t.Fatal(err)
	}
	got := CheckDrift(dir)
	if len(got) != 1 || got[0].Status != DriftStatusOK {
		t.Fatalf("CheckDrift = %+v, want OK: a newer package.json with the same deps is not drift", got)
	}
}

func TestCheckDriftMalformedFilesNeverPanic(t *testing.T) {
	names := []string{"package.json", "package-lock.json", "pnpm-lock.yaml", "Cargo.toml", "Cargo.lock", "go.mod", "go.sum", "composer.json", "composer.lock", "pyproject.toml", "poetry.lock", "Pipfile", "Pipfile.lock"}
	for _, garbage := range []string{"", "{", "\x00\xff", "[[package]]\nname = ", "importers:\n  .: [\n", "require (\n", "packages: 7\n", "{\"packages\": {\"\": 5}}"} {
		files := map[string]string{}
		for _, n := range names {
			files[n] = garbage
		}
		dir, _ := projectWith(t, files)
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("CheckDrift panicked on %q: %v", garbage, r)
				}
			}()
			for _, d := range CheckDrift(dir) {
				if d.Status == DriftStatusOutdated && garbage == "" {
					t.Errorf("empty files reported as outdated: %+v", d)
				}
			}
			_ = ScanProject(dir)
		}()
	}
}

func TestScanProjectRequiresOnlyRealLockfiles(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  []string
	}{
		{"PEP 621 pyproject needs no lockfile", map[string]string{"pyproject.toml": "[project]\nname = \"x\"\ndependencies = [\"requests\"]\n"}, nil},
		{"PEP 621 with uv.lock", map[string]string{"pyproject.toml": "[project]\nname = \"x\"\n", "uv.lock": "version = 1\n"}, nil},
		{"poetry project needs poetry.lock", map[string]string{"pyproject.toml": "[tool.poetry]\nname = \"x\"\n"}, []string{"poetry.lock"}},
		{"poetry project with poetry.lock", map[string]string{"pyproject.toml": "[tool.poetry]\nname = \"x\"\n", "poetry.lock": ""}, nil},
		{"requirements.txt never needs requirements.lock", map[string]string{"requirements.txt": "requests\n"}, nil},
		{"package.json with bun.lock", map[string]string{"package.json": "{}", "bun.lock": "{}"}, nil},
		{"package.json alone", map[string]string{"package.json": "{}"}, []string{"package-lock.json"}},
		{"go.mod without requirements", map[string]string{"go.mod": "module example.com/x\n\ngo 1.22\n"}, nil},
		{"go.mod requiring only a local replacement", map[string]string{"go.mod": "module example.com/x\n\ngo 1.22\n\nrequire example.com/y v0.0.0\n\nreplace example.com/y => ../y\n"}, nil},
		{"go.mod with requirements", map[string]string{"go.mod": goModTwoRequires}, []string{"go.sum"}},
		{"Cargo.toml alone", map[string]string{"Cargo.toml": cargoToml}, []string{"Cargo.lock"}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, scan := projectWith(t, c.files)
			if !reflect.DeepEqual(scan.MissingLockFiles, c.want) {
				t.Errorf("MissingLockFiles = %q, want %q", scan.MissingLockFiles, c.want)
			}
		})
	}
}

func TestMissingLockfileIsCountedOnce(t *testing.T) {
	dir, scan := projectWith(t, map[string]string{"package.json": pkgJSONExpressJest})
	report := Report{Project: scan, Drift: CheckDrift(dir)}
	if len(report.Drift) != 0 {
		t.Fatalf("Drift = %+v, want no entry for an absent lockfile", report.Drift)
	}
	cfg := Config{SkipEnv: true, SkipSecurity: true, SkipConflicts: true}
	good, bad, warn := summarize(report, cfg)
	if good != 0 || bad != 1 || warn != 0 {
		t.Fatalf("summarize = %d passed, %d failed, %d warnings; want 0 1 0", good, bad, warn)
	}
	if !HasIssues(report) {
		t.Fatal("HasIssues = false with a missing lockfile")
	}
}

func TestRunUsesConfigDir(t *testing.T) {
	dir, _ := projectWith(t, map[string]string{"package.json": pkgJSONExpressJest})
	// No binary is "installed", so the package-manager checks run nothing.
	withFakeAudit(t, &fakeAudit{})
	report := Run(Config{Dir: dir, SkipEnv: true, SkipSecurity: true})
	if !reflect.DeepEqual(report.Project.MissingLockFiles, []string{"package-lock.json"}) {
		t.Fatalf("MissingLockFiles = %q, want [package-lock.json] from Config.Dir", report.Project.MissingLockFiles)
	}
}
